version: '3'
services:
  app:
    restart: always
    container_name: nexus
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./configs:/configs
      - ./src:/src
    working_dir: /src
    ports:
      - "9001:9001"
